Auth
VladimirUman/cinema-client pull request #11
Opened 2022-02-08 10:13 UTC by VladimirUman

2022-02-08 10:42 UTC, MaxLogvyniukFive requested changes

2022-02-08 10:42 UTC, MaxLogvyniukFive commented on src/services/authentication.js
> +        accessTokenSubject.next(null);
What this code do?

2022-02-08 12:56 UTC, VladimirUman commented on src/services/authentication.js
> +        accessTokenSubject.next(null);
update observable token object

2022-02-09 07:01 UTC, MaxLogvyniukFive approved these changes

2022-02-09 08:53 UTC, merged

2022-02-09 09:30 UTC, MaxLogvyniukFive commented on src/api/index.js
> +            if (err.response.status === 419 && !originalConfig._retry) {
Put 419 in variable

2022-02-09 09:30 UTC, MaxLogvyniukFive commented on src/services/authentication.js
> +        currentUserSubject.next(null);
What does this action do?